In [8]:
import pandas as pd
import os

# From web server

This certainly works in a few simple instances, where we know the link of interest and can directly plug it into pandas and get a dataframe. However, it is hard to traverse for a dataset of interest in a programatic way.. which is where and API would come in.

For now though, I'm really only interested in getting a somewhat recent view of things so maybe like the past 5 years is the focus as I go for a bit of a breadth first approach. Perhaps a deeper dive in to historical data would also be nice / worth looking into later. I just don't know how much overlap I'll be able to get in various metrics across different years (maybe something that was measured in 2017 wasn't measured in 2018), so I just want to get as much as I can within reason.

In [2]:

# Define URL for Census data
# url = 'https://www2.census.gov/programs-surveys/popest/datasets/2020/state/detail/SCPRC-EST2020-18+POP-RES.csv'
url = "https://www2.census.gov/programs-surveys/popest/datasets/2020-2022/state/totals/NST-EST2022-ALLDATA.csv"
# Read CSV data into pandas DataFrame
df_population = pd.read_csv(url)

# Rename column to 'population'
df_population

,SUMLEV,REGION,DIVISION,STATE,NAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,NPOPCHG_2020,...,RDEATH2021,RDEATH2022,RNATURALCHG2021,RNATURALCHG2022,RINTERNATIONALMIG2021,RINTERNATIONALMIG2022,RDOMESTICMIG2021,RDOMESTICMIG2022,RNETMIG2021,RNETMIG2022
0,10,0,0,0,United States,331449520,331511512,332031554,333287557,61992,...,10.363828,10.350218,0.434073,0.736729,1.133397,3.038912,0.000000,0.000000,1.133397,3.038912
1,20,1,0,0,Northeast Region,57609156,57448898,57259257,57040406,-160258,...,9.780142,9.868918,0.206629,0.511200,1.402708,3.752662,-4.855348,-8.061896,-3.452640,-4.309234
2,30,1,1,0,New England,15116206,15074473,15121745,15129548,-41733,...,9.530598,9.887115,-0.310502,-0.206669,1.770752,4.655140,1.546021,-3.767839,3.316773,0.887301
3,30,1,2,0,Middle Atlantic,42492950,42374425,42137512,41910858,-118525,...,9.869304,9.862369,0.391400,0.769581,1.271205,3.427836,-7.142565,-9.607444,-5.871360,-6.179608
4,20,2,0,0,Midwest Region,68985537,68961043,68836505,68787595,-24494,...,11.059195,11.169148,-0.207043,-0.125530,0.802714,2.111084,-2.645374,-2.529339,-1.842660,-0.418255
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,40,4,9,53,Washington,7705247,7724031,7740745,7785786,18784,...,8.400898,9.117040,2.264113,1.737928,1.809144,4.831987,-1.990071,-0.461146,-0.180927,4.370841
62,40,3,5,54,West Virginia,1793755,1791420,1785526,1775156,-2335,...,15.341020,16.649619,-5.665727,-6.829029,0.406492,0.995877,1.602484,0.266241,2.008976,1.262118
63,40,2,3,55,Wisconsin,5893725,5896271,5880101,5892539,2546,...,10.496442,10.770227,-0.305357,-0.298659,0.541593,1.388643,-3.209987,1.300813,-2.668394,2.689456
64,40,4,8,56,Wyoming,576837,577605,579483,581381,768,...,10.706187,11.506947,-0.063954,-0.844199,0.233344,0.589216,3.085331,3.707583,3.318676,4.296800
65,40,X,X,72,Puerto Rico,3285874,3281557,3262693,3221789,-4317,...,10.189403,10.518034,-4.445735,-4.458953,-1.319326,-8.157012,0.000000,0.000000,-1.319326,-8.157012

In [3]:
df_population.columns

Index(['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'NAME', 'ESTIMATESBASE2020',
       'POPESTIMATE2020', 'POPESTIMATE2021', 'POPESTIMATE2022', 'NPOPCHG_2020',
       'NPOPCHG_2021', 'NPOPCHG_2022', 'BIRTHS2020', 'BIRTHS2021',
       'BIRTHS2022', 'DEATHS2020', 'DEATHS2021', 'DEATHS2022',
       'NATURALCHG2020', 'NATURALCHG2021', 'NATURALCHG2022',
       'INTERNATIONALMIG2020', 'INTERNATIONALMIG2021', 'INTERNATIONALMIG2022',
       'DOMESTICMIG2020', 'DOMESTICMIG2021', 'DOMESTICMIG2022', 'NETMIG2020',
       'NETMIG2021', 'NETMIG2022', 'RESIDUAL2020', 'RESIDUAL2021',
       'RESIDUAL2022', 'RBIRTH2021', 'RBIRTH2022', 'RDEATH2021', 'RDEATH2022',
       'RNATURALCHG2021', 'RNATURALCHG2022', 'RINTERNATIONALMIG2021',
       'RINTERNATIONALMIG2022', 'RDOMESTICMIG2021', 'RDOMESTICMIG2022',
       'RNETMIG2021', 'RNETMIG2022'],
      dtype='object')

In [4]:
population_size_df = df_population[['REGION', 'DIVISION', 'STATE', 'NAME'] + [f"POPESTIMATE{year}" for year in range(2020,2023)]].query("STATE not in [0] and NAME not in ['Puerto Rico', 'District of Columbia']")
population_size_df

,REGION,DIVISION,STATE,NAME,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022
14,3,6,1,Alabama,5031362,5049846,5074296
15,4,9,2,Alaska,732923,734182,733583
16,4,8,4,Arizona,7179943,7264877,7359197
17,3,7,5,Arkansas,3014195,3028122,3045637
18,4,9,6,California,39501653,39142991,39029342
19,4,8,8,Colorado,5784865,5811297,5839926
20,1,1,9,Connecticut,3597362,3623355,3626205
21,3,5,10,Delaware,992114,1004807,1018396
23,3,5,12,Florida,21589602,21828069,22244823
24,3,5,13,Georgia,10729828,10788029,10912876
25,4,9,15,Hawaii,1451043,1447154,1440196
26,4,8,16,Idaho,1849202,1904314,1939033
27,2,3,17,Illinois,12786580,12686469,12582032
28,2,3,18,Indiana,6788799,6813532,6833037
29,2,4,19,Iowa,3190571,3197689,3200517
30,2,4,20,Kansas,2937919,2937922,2937150
31,3,6,21,Kentucky,4507445,4506589,4512310
32,3,7,22,Louisiana,4651664,4627098,4590241
33,1,1,23,Maine,1363557,1377238,1385340
34,3,5,24,Maryland,6173205,6174610,6164660
35,1,1,25,Massachusetts,6995729,6989690,6981974
36,2,3,26,Michigan,10069577,10037504,10034113
37,2,4,27,Minnesota,5709852,5711471,5717184
38,3,6,28,Mississippi,2958141,2949586,2940057
39,2,4,29,Missouri,6153998,6169823,6177957
40,4,8,30,Montana,1087075,1106227,1122867
41,2,4,31,Nebraska,1962642,1963554,1967923
42,4,8,32,Nevada,3115648,3146402,3177772
43,1,1,33,New Hampshire,1378587,1387505,1395231
44,1,2,34,New Jersey,9271689,9267961,9261699
45,4,8,35,New Mexico,2118390,2116677,2113344
46,1,2,36,New York,20108296,19857492,19677151
47,3,5,37,North Carolina,10449445,10565885,10698973
48,2,4,38,North Dakota,779518,777934,779261
49,2,3,39,Ohio,11797517,11764342,11756058
50,3,7,40,Oklahoma,3964912,3991225,4019800
51,4,9,41,Oregon,4244795,4256301,4240137
52,1,2,42,Pennsylvania,12994440,13012059,12972008
53,1,1,44,Rhode Island,1096345,1096985,1093734
54,3,5,45,South Carolina,5131848,5193266,5282634
55,2,4,46,South Dakota,887799,896164,909824
56,3,6,47,Tennessee,6925619,6968351,7051339
57,3,7,48,Texas,29232474,29558864,30029572
58,4,8,49,Utah,3283785,3339113,3380800
59,1,1,50,Vermont,642893,646972,647064
60,3,5,51,Virginia,8636471,8657365,8683619
61,4,9,53,Washington,7724031,7740745,7785786
62,3,5,54,West Virginia,1791420,1785526,1775156
63,2,3,55,Wisconsin,5896271,5880101,5892539
64,4,8,56,Wyoming,577605,579483,581381

Yes! That's basically what I want! I think this will also serve as the basis for lots of per capita metrics to keep from getting a bunch of repeated population metrics.

What I want to do with this is save it as three separate files

- data
    - 2021
        - population_size.csv
    - 2022
        - population_size.csv
    - 2023
        - population_size.csv

With the following columns:
    - state
    - rank
    - population_size

In [5]:
def metric_rank(df, state_name, metric_name, new_metric_name):
    metric_df = df.copy()[[state_name,metric_name]].rename(columns={state_name:"state",metric_name:new_metric_name})
    metric_df["rank"] = metric_df[new_metric_name].rank(ascending=False)
    return metric_df.sort_values("rank")

In [6]:
metric_rank(population_size_df, "NAME","POPESTIMATE2020","population_size")

             state  population_size  rank
18      California         39501653   1.0
57           Texas         29232474   2.0
23         Florida         21589602   3.0
46        New York         20108296   4.0
52    Pennsylvania         12994440   5.0
27        Illinois         12786580   6.0
49            Ohio         11797517   7.0
24         Georgia         10729828   8.0
47  North Carolina         10449445   9.0
36        Michigan         10069577  10.0
44      New Jersey          9271689  11.0
60        Virginia          8636471  12.0
61      Washington          7724031  13.0
16         Arizona          7179943  14.0
35   Massachusetts          6995729  15.0
56       Tennessee          6925619  16.0
28         Indiana          6788799  17.0
34        Maryland          6173205  18.0
39        Missouri          6153998  19.0
63       Wisconsin          5896271  20.0
19        Colorado          5784865  21.0
37       Minnesota          5709852  22.0
54  South Carolina          5131848  23.0
14         Alabama          5031362  24.0
32       Louisiana          4651664  25.0
31        Kentucky          4507445  26.0
51          Oregon          4244795  27.0
50        Oklahoma          3964912  28.0
20     Connecticut          3597362  29.0
58            Utah          3283785  30.0
29            Iowa          3190571  31.0
42          Nevada          3115648  32.0
17        Arkansas          3014195  33.0
38     Mississippi          2958141  34.0
30          Kansas          2937919  35.0
45      New Mexico          2118390  36.0
41        Nebraska          1962642  37.0
26           Idaho          1849202  38.0
62   West Virginia          1791420  39.0
25          Hawaii          1451043  40.0
43   New Hampshire          1378587  41.0
33           Maine          1363557  42.0
53    Rhode Island          1096345  43.0
40         Montana          1087075  44.0
21        Delaware           992114  45.0
55    South Dakota           887799  46.0
48    North Dakota           779518  47.0
15          Alaska           732923  48.0
59         Vermont           642893  49.0
64         Wyoming           577605  50.0

Yep! That's pretty clean! Should be pretty straight forward to just iterate over the years and grab these / dump them where I want them to go! Also, I definitely think this function will be a workhorse moving forward when I grab other datasets of interest!

In [12]:
for year in range(2020,2023):
    if not os.path.exists(f"../data/{year}"):
        os.makedirs(f"../data/{year}")
    metric_rank(population_size_df, "NAME",f"POPESTIMATE{year}","population_size").to_csv(f"../data/{year}/population_size.csv",index = None)

In [7]:
population_size_2020 = population_size_df.copy()[["NAME","POPESTIMATE2020"]]
population_size_2020["rank"] = population_size_df["POPESTIMATE2020"].rank(ascending=False)
population_size_2020.sort_values("rank")

              NAME  POPESTIMATE2020  rank
18      California         39501653   1.0
57           Texas         29232474   2.0
23         Florida         21589602   3.0
46        New York         20108296   4.0
52    Pennsylvania         12994440   5.0
27        Illinois         12786580   6.0
49            Ohio         11797517   7.0
24         Georgia         10729828   8.0
47  North Carolina         10449445   9.0
36        Michigan         10069577  10.0
44      New Jersey          9271689  11.0
60        Virginia          8636471  12.0
61      Washington          7724031  13.0
16         Arizona          7179943  14.0
35   Massachusetts          6995729  15.0
56       Tennessee          6925619  16.0
28         Indiana          6788799  17.0
34        Maryland          6173205  18.0
39        Missouri          6153998  19.0
63       Wisconsin          5896271  20.0
19        Colorado          5784865  21.0
37       Minnesota          5709852  22.0
54  South Carolina          5131848  23.0
14         Alabama          5031362  24.0
32       Louisiana          4651664  25.0
31        Kentucky          4507445  26.0
51          Oregon          4244795  27.0
50        Oklahoma          3964912  28.0
20     Connecticut          3597362  29.0
58            Utah          3283785  30.0
29            Iowa          3190571  31.0
42          Nevada          3115648  32.0
17        Arkansas          3014195  33.0
38     Mississippi          2958141  34.0
30          Kansas          2937919  35.0
45      New Mexico          2118390  36.0
41        Nebraska          1962642  37.0
26           Idaho          1849202  38.0
62   West Virginia          1791420  39.0
25          Hawaii          1451043  40.0
43   New Hampshire          1378587  41.0
33           Maine          1363557  42.0
53    Rhode Island          1096345  43.0
40         Montana          1087075  44.0
21        Delaware           992114  45.0
55    South Dakota           887799  46.0
48    North Dakota           779518  47.0
15          Alaska           732923  48.0
59         Vermont           642893  49.0
64         Wyoming           577605  50.0